import random
import json

from fastapi import FastAPI

app = FastAPI() #creates the application that handles incoming requests and routes them to the appropriate endpoints.

@app.get("/") # when someone sends a GET request to the root URL ("/"), the read_root function will be called.
def read_root():
    return {"message": "Job queue service is running"}

jobs = {} #tracker
job_counter = 0  #each job submitted to the queue will be assigned a unique job ID, which is generated by incrementing the job_counter variable. The jobs dictionary will store the status of each job, with the job ID as the key and a dictionary containing the job's status as the value.


import time
import threading

def process_job(job_id):
    time.sleep(5) #time.sleep(5) simulates a time-consuming job by pausing the execution of the process_job function for 5 seconds. This is done to mimic the behavior of a real job that takes some time to complete.
    if  random.random()  < 0.3: #random.random() generates a random float between 0 and 1. If the generated number is less than 0.3 (30% chance), the job is considered to have failed.
        jobs[job_id]["attempts"] += 1
        if jobs[job_id]["attempts"] < jobs[job_id]["max_attempts"]:
            jobs[job_id]["status"] = "queued"
            thread = threading.Thread(target=process_job, args=(job_id,))
            thread.start()

        elif jobs[job_id]["attempts"] >= jobs[job_id]["max_attempts"]:
            jobs[job_id]["status"] = "failed"
            jobs[job_id]["result"] = "job failed after maximum attempts"
            with open(f"results/{job_id}.json", "w") as f:
                json.dump(jobs[job_id], f)

        
    else:
        jobs[job_id]["status"] = "completed"
        jobs[job_id]["result"] = "job finished successfully"
        with open(f"results/{job_id}.json", "w") as f:
            json.dump(jobs[job_id], f)

@app.post("/submit-job")
def submit_job():
    global job_counter #assigns a new job ID to the submitted job, adds it to the jobs dictionary with a status of "queued", and starts a new thread to process the job asynchronously. The function returns a JSON response containing the job ID and its initial status.
    job_counter += 1
    job_id = job_counter
    jobs[job_id] = {"status": "queued", "attempts": 0, "max_attempts": 5}
    
    thread = threading.Thread(target=process_job, args=(job_id,)) #tells  pyhton to create a new thread that will run the process_job function with the job_id as an argument. This allows the job to be processed in the background while the main application continues to handle incoming requests.
    thread.start()
    
    return {"job_id": job_id, "status": "queued"}

@app.get("/job-status/{job_id}")
def get_job_status(job_id: int): #tells FastAPI to expect an integer parameter named job_id in the URL path. The function retrieves the status of the job with the specified job ID from the jobs dictionary and returns it as a JSON response. If the job ID is not found in the jobs dictionary, it returns an error message indicating that the job was not found.
    if job_id not in jobs:
        return {"error": "Job not found"}
    return jobs[job_id]
